import AuthProvider from "@/features/auth/components/AuthProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import Breadcrumbs from "@/components/ui/Breadcrumbs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Habit tracker",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main className="flex min-h-screen justify-center p-8 md:p-16 bg-gradient-to-b from-sky-400 to-purple-400">
                    <AuthProvider
                        fallback={
                            <div className="w-full max-w-5xl">
                                <div className="mb-5">
                                    <Breadcrumbs segments={["loading..."]} />
                                </div>
                                <div className="rounded-lg bg-sky-200 p-6 h-56 max-h-screen"></div>
                            </div>
                        }
                    >
                        {children}
                    </AuthProvider>
                </main>
            </body>
        </html>
    );
}
