import AuthProvider from "@/features/auth/components/AuthProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Habit tracker",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider fallback={<div>loading...</div>}>
                    {children}
                </AuthProvider>
            </body>
        </html>
    );
}
