import AuthProvider from "@/features/auth/components/AuthProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import Breadcrumbs from "@/components/ui/Breadcrumbs";
import Skeleton from "@/components/ui/Skeleton";
import HabitsProvider from "@/features/habits/components/HabitsProvider";
import { CgSpinner } from "react-icons/cg";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Habit tracker",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="text-sm sm:text-base">
            <body className={inter.className}>
                <main className="flex min-h-screen justify-center px-3 py-6 sm:p-8 md:p-16 bg-gradient-to-b from-sky-400 to-purple-400">
                    <AuthProvider
                        fallback={
                            <div className="text-center">
                                <div>
                                    <Breadcrumbs segments={["loading..."]} />
                                </div>
                                <div className="mt-10 text-center">
                                    <CgSpinner className="w-10 h-10 inline text-sky-200 animate-spin" />
                                </div>
                            </div>
                        }
                    >
                        <HabitsProvider>{children}</HabitsProvider>
                    </AuthProvider>
                </main>
            </body>
        </html>
    );
}
